name: Encode and Commit File to Base64

on:
  workflow_dispatch:

jobs:
  encode_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Encode file to Base64
      run: |
        FILE_TO_ENCODE="pac_decoded.txt"
        ENCODED_FILE="pac.txt"
        
        # Encode the file to Base64 and save it to a new file
        base64 -b 64 -i "$FILE_TO_ENCODE" -o "$ENCODED_FILE"
        
        # Print the encoded content (for logging purposes)
        cat "$ENCODED_FILE"

    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add "$ENCODED_FILE"
        git commit -m "Encode $FILE_TO_ENCODE to Base64"
        git push origin main
